// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_todos

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Rule struct {
	Targets       []*string `json:"targets"`
	Doublecolon   bool      `json:"doublecolon"`
	Commands      []*string `json:"commands"`
	Prereqs       []*string `json:"prereqs"`
	Targetpattern string    `json:"targetpattern"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Variable struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}
